#!/usr/bin/env python3
"""Generate and verify the reusable Kungfu Publications design system."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DESIGN_ROOT = ROOT / "design-system"
COLORS_PATH = DESIGN_ROOT / "tokens/colors.json"
TYPOGRAPHY_PATH = DESIGN_ROOT / "tokens/typography.json"
LAYOUT_PATH = DESIGN_ROOT / "tokens/layout.json"
ASSET_MANIFEST_PATH = DESIGN_ROOT / "assets/manifest.json"
STYLE_PATH = DESIGN_ROOT / "styles/kungfu-publications.sty"
PDF_RENDERERS = (
    ROOT / "scripts/render_atlas_lite_guide.py",
    ROOT / "scripts/render_atlas_lite_intro.py",
)


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def tex_font_choice(fonts: list[str], commands: list[str], error_label: str) -> str:
    if not fonts:
        return rf"\PackageError{{kungfu-publications}}{{No {error_label} font is available}}{{Install a documented font fallback}}"
    font = fonts[0]
    body = "\n".join(command.format(font=font) for command in commands)
    if len(fonts) == 1:
        fallback = rf"\PackageError{{kungfu-publications}}{{No {error_label} font is available}}{{Install {font}}}"
    else:
        fallback = tex_font_choice(fonts[1:], commands, error_label)
    return "\n".join(
        (
            rf"\IfFontExistsTF{{{font}}}{{%",
            body,
            "}{%",
            fallback,
            "}",
        )
    )


def render_style() -> str:
    colors = load_json(COLORS_PATH)
    typography = load_json(TYPOGRAPHY_PATH)
    layout = load_json(LAYOUT_PATH)
    families = typography["families"]

    latin = tex_font_choice(
        [families["latin_sans"]["primary"], *families["latin_sans"]["fallbacks"]],
        [r"\setmainfont{{{font}}}", r"\setsansfont{{{font}}}"],
        "Latin sans-serif",
    )
    cjk = tex_font_choice(
        [families["cjk_sans"]["primary"], *families["cjk_sans"]["fallbacks"]],
        [r"\setCJKmainfont{{{font}}}", r"\setCJKsansfont{{{font}}}", r"\setCJKmonofont{{{font}}}"],
        "CJK sans-serif",
    )
    mono_scale = families["mono"]["scale"]
    mono = tex_font_choice(
        [families["mono"]["primary"], *families["mono"]["fallbacks"]],
        [r"\setmonofont{{{font}}}[Scale=" + str(mono_scale) + "]"],
        "monospaced",
    )
    color_lines = "\n".join(
        rf"\definecolor{{{color['tex_name']}}}{{HTML}}{{{color['hex']}}}"
        for color in colors["colors"]
    )
    dimension_lines = "\n".join(
        rf"\newcommand{{\{token['tex_macro']}}}{{{token['value']}}}"
        for section in ("spacing", "radii")
        for token in layout[section]
    )
    return f"""% Generated by scripts/design_system.py. Edit design-system/tokens/, not this file.
\\NeedsTeXFormat{{LaTeX2e}}
\\ProvidesPackage{{kungfu-publications}}[2026/08/26 v1.0 Kungfu Publications design tokens]
\\RequirePackage{{fontspec}}
\\RequirePackage{{xeCJK}}
\\RequirePackage[table]{{xcolor}}

{latin}
{cjk}
{mono}
\\renewcommand{{\\familydefault}}{{\\sfdefault}}

{color_lines}

{dimension_lines}
\\newcommand{{\\KFBrandName}}{{KUNGFU PUBLICATIONS}}
\\newcommand{{\\KFAtlasLiteName}}{{ATLAS LITE}}
"""


def validate_tokens() -> set[str]:
    colors = load_json(COLORS_PATH)
    if colors.get("schema") != "kungfu.publications.colors/v1":
        raise ValueError("unsupported color token schema")
    seen_ids: set[str] = set()
    seen_names: set[str] = set()
    allowed_hex: set[str] = set()
    for color in colors.get("colors", []):
        color_id = color.get("id", "")
        tex_name = color.get("tex_name", "")
        hex_value = color.get("hex", "")
        if not re.fullmatch(r"[a-z][a-z0-9-]*", color_id):
            raise ValueError(f"invalid color id: {color_id}")
        if not re.fullmatch(r"KF[A-Za-z0-9]+", tex_name):
            raise ValueError(f"invalid TeX color name: {tex_name}")
        if not re.fullmatch(r"[0-9A-F]{6}", hex_value):
            raise ValueError(f"invalid color hex: {hex_value}")
        if color_id in seen_ids or tex_name in seen_names or hex_value in allowed_hex:
            raise ValueError(f"duplicate color token: {color_id}")
        seen_ids.add(color_id)
        seen_names.add(tex_name)
        allowed_hex.add(hex_value)

    typography = load_json(TYPOGRAPHY_PATH)
    if typography.get("schema") != "kungfu.publications.typography/v1":
        raise ValueError("unsupported typography token schema")
    for family in ("latin_sans", "cjk_sans", "mono"):
        spec = typography.get("families", {}).get(family, {})
        if not spec.get("primary") or not spec.get("fallbacks"):
            raise ValueError(f"font family requires primary and fallbacks: {family}")

    layout = load_json(LAYOUT_PATH)
    if layout.get("schema") != "kungfu.publications.layout/v1":
        raise ValueError("unsupported layout token schema")
    for section in ("spacing", "radii"):
        for token in layout.get(section, []):
            if not re.fullmatch(r"KF[A-Za-z0-9]+", token.get("tex_macro", "")):
                raise ValueError(f"invalid dimension macro: {token}")
            if not re.fullmatch(r"[0-9.]+(?:pt|mm|in|em)", token.get("value", "")):
                raise ValueError(f"invalid dimension value: {token}")
    return allowed_hex


def validate_assets(allowed_hex: set[str]) -> None:
    manifest = load_json(ASSET_MANIFEST_PATH)
    if manifest.get("schema") != "kungfu.publications.asset-manifest/v1":
        raise ValueError("unsupported asset manifest schema")
    declared: set[Path] = set()
    ids: set[str] = set()
    for asset in manifest.get("assets", []):
        asset_id = asset.get("id", "")
        if not re.fullmatch(r"[a-z][a-z0-9-]*", asset_id):
            raise ValueError(f"invalid asset id: {asset_id}")
        if asset_id in ids:
            raise ValueError(f"duplicate asset id: {asset_id}")
        ids.add(asset_id)
        relative_path = Path(asset["path"])
        if relative_path.is_absolute() or ".." in relative_path.parts or relative_path.suffix != ".svg":
            raise ValueError(f"asset path must be a relative SVG path: {relative_path}")
        path = DESIGN_ROOT / relative_path
        declared.add(path.resolve())
        if not path.is_file():
            raise ValueError(f"missing declared asset: {path.relative_to(ROOT)}")
        if not asset.get("alt_zh") or not asset.get("usage"):
            raise ValueError(f"asset metadata is incomplete: {asset_id}")
        root = ET.parse(path).getroot()
        if not root.tag.endswith("svg") or not root.get("viewBox"):
            raise ValueError(f"invalid SVG root or viewBox: {path.relative_to(ROOT)}")
        children = list(root)
        tags = {child.tag.rsplit("}", 1)[-1] for child in children}
        if "title" not in tags or "desc" not in tags:
            raise ValueError(f"SVG requires title and desc: {path.relative_to(ROOT)}")
        text = path.read_text(encoding="utf-8")
        if "data:image" in text or re.search(r"<image\b", text):
            raise ValueError(f"raster embedding is not allowed: {path.relative_to(ROOT)}")
        used_hex = {value.upper() for value in re.findall(r"#([0-9A-Fa-f]{6})", text)}
        unknown = used_hex - allowed_hex
        if unknown:
            raise ValueError(f"asset uses colors outside the token palette: {path.relative_to(ROOT)} {sorted(unknown)}")
    actual = {path.resolve() for path in (DESIGN_ROOT / "assets").rglob("*.svg")}
    if actual != declared:
        missing = sorted(str(path.relative_to(DESIGN_ROOT)) for path in actual - declared)
        stale = sorted(str(path.relative_to(DESIGN_ROOT)) for path in declared - actual)
        raise ValueError(f"asset manifest mismatch; undeclared={missing}, missing={stale}")


def verify() -> None:
    allowed_hex = validate_tokens()
    expected = render_style()
    if not STYLE_PATH.is_file() or STYLE_PATH.read_text(encoding="utf-8") != expected:
        raise SystemExit("stale design style: run make design")
    validate_assets(allowed_hex)
    for template in ("guide-a4.tex", "slides-16x9.tex"):
        path = DESIGN_ROOT / "templates" / template
        if not path.is_file():
            raise ValueError(f"missing design template: {template}")
        content = path.read_text(encoding="utf-8")
        if r"\usepackage{kungfu-publications}" not in content:
            raise ValueError(f"template does not consume the shared style: {template}")
        if re.search(r"\\(?:definecolor|setmainfont|setsansfont|setmonofont|setCJK\w*font)", content):
            raise ValueError(f"template duplicates shared visual tokens: {template}")
    for path in PDF_RENDERERS:
        content = path.read_text(encoding="utf-8")
        if r"\usepackage{kungfu-publications}" not in content or "install_tex_style(build_dir)" not in content:
            raise ValueError(f"PDF renderer does not install and consume the shared style: {path.name}")
        if re.search(r"\\(?:definecolor|setmainfont|setsansfont|setmonofont|setCJK\w*font)", content):
            raise ValueError(f"PDF renderer duplicates shared visual tokens: {path.name}")
    print("verified Kungfu Publications design system")


def generate() -> None:
    validate_tokens()
    STYLE_PATH.parent.mkdir(parents=True, exist_ok=True)
    STYLE_PATH.write_text(render_style(), encoding="utf-8")
    print(STYLE_PATH.relative_to(ROOT))


def install_tex_style(build_dir: Path) -> Path:
    expected = render_style()
    if not STYLE_PATH.is_file() or STYLE_PATH.read_text(encoding="utf-8") != expected:
        raise RuntimeError("design style is stale; run make design")
    build_dir.mkdir(parents=True, exist_ok=True)
    target = build_dir / STYLE_PATH.name
    shutil.copy2(STYLE_PATH, target)
    return target


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("generate", "verify"))
    args = parser.parse_args()
    if args.command == "generate":
        generate()
    else:
        verify()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
